INSERT INTO ingredients 
  (name_EN,tag_id,source,created_at,updated_at) 
VALUES 
  ('haddock',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hake',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('halibut',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('herring',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mackerel',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mahi-mahi',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('marlin',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('monkfish',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('angler fish',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('lotte',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('orange roughy',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('perch',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('pickerel',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('dore',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('walleye',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('pike',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('plaice',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('pollock',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('pompano',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('porgy',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('rockfish',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('salmon',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('sardine',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('shark',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('smelt',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('snapper',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('sole',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('sturgeon',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('swordfish',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('tilapia',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ("St. Peter's fish",4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('trout',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('tuna',4,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('albacore',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('bonito',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('turbot',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('white fish',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('whiting',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Crab',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crayfish',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crawfish',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('écrevisse',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('lobster',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('langouste',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('langoustine',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('coral',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('tomalley',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('prawns',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('shrimp',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('crevette',2,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Abalone',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('clam',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('cockle',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('conch',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('limpets',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('mussels',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('octopus',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('oysters',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('periwinkle',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('quahaugs',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('scallops',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('land and sea snails',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('squid',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('whelks',14,'http://www.hc-sc.gc.ca/fn-an/pubs/securit/2012-allergen_fish-poisson/index-eng.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Pangasius',4,'http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=COM:2003:0601:FIN:EN:PDF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('sea bass',4,'http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=COM:2003:0601:FIN:EN:PDF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('sheatfish',4,'http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=COM:2003:0601:FIN:EN:PDF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);