INSERT INTO ingredient_names 
  (expression;ingredient_id;Language;Source) 
VALUES 
  ('wheat;1;EN;'),
  ('rye;2;EN;'),
  ('barley;3;EN;'),
  ('oats;4;EN;'),
  ('spelt;5;EN;'),
  ('kamut;6;EN;'),
  ('seafood;7;EN;'),
  ('shrimp;8;EN;'),
  ('gamba;9;EN;'),
  ('egg;10;EN;'),
  ('eggs;11;EN;'),
  ('fish;12;EN;'),
  ('peanut;13;EN;'),
  ('peanut;14;EN;'),
  ('peanut butter;15;EN;'),
  ('peanut oil;16;EN;'),
  ('soja;17;EN;'),
  ('soy;18;EN;'),
  ('soya;19;EN;'),
  ('soja oil;20;EN;'),
  ('soy oil;21;EN;'),
  ('milk;22;EN;'),
  ('lactose;23;EN;'),
  ('almonds;24;EN;'),
  ('hazelnuts;25;EN;'),
  ('walnuts;26;EN;'),
  ('cashews;27;EN;'),
  ('pecan nuts;28;EN;'),
  ('Brazil nuts;29;EN;'),
  ('pistachio nuts;30;EN;'),
  ('macadamia nuts;31;EN;'),
  ('Queensland nuts;32;EN;'),
  ('celery;33;EN;'),
  ('mustard;34;EN;'),
  ('mustard seed;35;EN;'),
  ('sesame;36;EN;'),
  ('sesame seeds;37;EN;'),
  ('sesame oil;38;EN;'),
  ('sulfure dioxide;39;EN;'),
  ('sulphites ;40;EN;'),
  ('lupin;41;EN;'),
  ('lupine;42;EN;'),
  ('mollusc;43;EN;'),
  ('Beta-lactoglobulin;44;EN;'),
  ('Casein;45;EN;'),
  ('rennet casein;46;EN;'),
  ('Caseinate;47;EN;'),
  ('ammonium caseinate;48;EN;'),
  ('calcium caseinate;49;EN;'),
  ('magnesium caseinate;50;EN;'),
  ('potassium caseinate;51;EN;'),
  ('sodium caseinate;52;EN;'),
  ('Delactosed or demineralized whey;53;EN;'),
  ('Hydrolyzed casein;54;EN;'),
  ('Lactalbumin;55;EN;'),
  ('lactalbumin phosphate;56;EN;'),
  ('Lactoferrin;57;EN;'),
  ('lactoglobulin;58;EN;'),
  ('Whey;59;EN;'),
  ('whey protein concentrate;60;EN;'),
  ('Butter;61;EN;'),
  ('Buttermilk;62;EN;'),
  ('Cheese;63;EN;'),
  ('curds;64;EN;'),
  ('Cream;65;EN;'),
  ('ice cream;66;EN;'),
  ('Ghee;67;EN;'),
  ('Kefir;68;EN;'),
  ('Kefir (milk drink);69;EN;'),
  ('Kumiss;70;EN;'),
  ('Kumiss (fermented milk drink);71;EN;'),
  ('Sour cream;72;EN;'),
  ('Yoghourt;73;EN;'),
  ('Albumin;74;EN;'),
  ('albumen;75;EN;'),
  ('Conalbumin;76;EN;'),
  ('Egg substitutes;77;EN;'),
  ('Globulin;78;EN;'),
  ('Livetin;79;EN;'),
  ('Lysozyme;80;EN;'),
  ('ovalbumin;81;EN;'),
  ('ovomucin;82;EN;'),
  ('ovotransferrin;83;EN;'),
  ('Silico-albuminate;84;EN;'),
  ('Vitellin;85;EN;'),
  ('Anchovy;86;EN;'),
  ('basa;87;EN;'),
  ('bass;88;EN;'),
  ('bluefish;89;EN;'),
  ('bream;90;EN;'),
  ('carp;91;EN;'),
  ('catfish;92;EN;'),
  ('channel cat;93;EN;'),
  ('mudcat;94;EN;'),
  ('char;95;EN;'),
  ('chub;96;EN;'),
  ('cisco;97;EN;'),
  ('cod;98;EN;'),
  ('eel;99;EN;'),
  ('flounder;100;EN;'),
  ('grouper;101;EN;'),
  ('haddock;102;EN;'),
  ('hake;103;EN;'),
  ('halibut;104;EN;'),
  ('herring;105;EN;'),
  ('mackerel;106;EN;'),
  ('mahi-mahi;107;EN;'),
  ('marlin;108;EN;'),
  ('monkfish;109;EN;'),
  ('angler fish;110;EN;'),
  ('lotte;111;EN;'),
  ('orange roughy;112;EN;'),
  ('perch;113;EN;'),
  ('pickerel;114;EN;'),
  ('dore;115;EN;'),
  ('walleye;116;EN;'),
  ('pike;117;EN;'),
  ('plaice;118;EN;'),
  ('pollock;119;EN;'),
  ('pompano;120;EN;'),
  ('porgy;121;EN;'),
  ('rockfish;122;EN;'),
  ('salmon;123;EN;'),
  ('sardine;124;EN;'),
  ('shark;125;EN;'),
  ('smelt;126;EN;'),
  ('snapper;127;EN;'),
  ('sole;128;EN;'),
  ('sturgeon;129;EN;'),
  ('swordfish;130;EN;'),
  ('tilapia;131;EN;'),
  ('St. Peter's fish;132;EN;'),
  ('trout;133;EN;'),
  ('tuna;134;EN;'),
  ('albacore;135;EN;'),
  ('bonito;136;EN;'),
  ('turbot;137;EN;'),
  ('white fish;138;EN;'),
  ('whiting;139;EN;'),
  ('Crab;140;EN;'),
  ('crayfish;141;EN;'),
  ('crawfish;142;EN;'),
  ('écrevisse;143;EN;'),
  ('lobster;144;EN;'),
  ('langouste;145;EN;'),
  ('langoustine;146;EN;'),
  ('coral;147;EN;'),
  ('tomalley;148;EN;'),
  ('prawns;149;EN;'),
  ('shrimp;150;EN;'),
  ('crevette;151;EN;'),
  ('Abalone;152;EN;'),
  ('clam;153;EN;'),
  ('cockle;154;EN;'),
  ('conch;155;EN;'),
  ('limpets;156;EN;'),
  ('mussels;157;EN;'),
  ('octopus;158;EN;'),
  ('oysters;159;EN;'),
  ('periwinkle;160;EN;'),
  ('quahaugs;161;EN;'),
  ('scallops;162;EN;'),
  ('land and sea snails;163;EN;'),
  ('squid;164;EN;'),
  ('whelks;165;EN;'),
  ('blé;1;FR;'),
  ('seigle;2;FR;'),
  ('orge;3;FR;'),
  ('avoine;4;FR;'),
  ('épeautre;5;FR;'),
  ('kamut;6;FR;'),
  ('fruits de mer;7;FR;'),
  ('crevettes;8;FR;'),
  ('gamba;9;FR;'),
  ('œuf;10;FR;'),
  ('œufs;11;FR;'),
  ('poisson;12;FR;'),
  ('cacahouète;13;FR;'),
  ('arachide;14;FR;'),
  ('beurre de cacahouète;15;FR;'),
  ('huile d'arachide;16;FR;'),
  ('soja;17;FR;'),
  ('soja;18;FR;'),
  ('soja;19;FR;'),
  ('huile de soja;20;FR;'),
  ('huile de soja;21;FR;'),
  ('lait;22;FR;'),
  ('lactose;23;FR;'),
  ('amandes;24;FR;'),
  ('noisettes;25;FR;'),
  ('noix;26;FR;'),
  ('noix de cajou;27;FR;'),
  ('noix de pécan;28;FR;'),
  ('noix du Brésil;29;FR;'),
  ('pistaches;30;FR;'),
  ('noix de Macadamia;31;FR;'),
  ('noix du Queensland;32;FR;'),
  ('céleri;33;FR;'),
  ('moutarde;34;FR;'),
  ('graines de moutarde;35;FR;'),
  ('sésame;36;FR;'),
  ('graines de sésame;37;FR;'),
  ('huile de sésame;38;FR;'),
  ('anhydride sulfureux;39;FR;'),
  ('sulfites;40;FR;'),
  ('lupin;41;FR;'),
  ('lupin;42;FR;'),
  ('mollusques;43;FR;'),
  ('Bêta-lactoglobuline;44;FR;'),
  ('Caséine;45;FR;'),
  ('caséine présure;46;FR;'),
  ('Caséinate;47;FR;'),
  ('caséinate d'ammonium;48;FR;'),
  ('caséinate de calcium;49;FR;'),
  ('caséinate de magnésium;50;FR;'),
  ('caséinate de potassium;51;FR;'),
  ('caséinate de sodium;52;FR;'),
  ('Petit-lait sans lactose ou déminéralisé;53;FR;'),
  ('Caséine hydrolysée;54;FR;'),
  ('Lactalbumine;55;FR;'),
  ('phosphate de lactalbumine;56;FR;'),
  ('Lactoferrine;57;FR;'),
  ('lactoglobuline;58;FR;'),
  ('Petit-lait;59;FR;'),
  ('concentré de protéines de petit-lait;60;FR;'),
  ('Beurre;61;FR;'),
  ('babeurre;62;FR;'),
  ('Fromage;63;FR;'),
  ('caillés;64;FR;'),
  ('Crème;65;FR;'),
  ('crème glacée;66;FR;'),
  ('Ghee;67;FR;'),
  ('Kéfir;68;FR;'),
  ('boisson à base de lait;69;FR;'),
  ('Koumis;70;FR;'),
  ('Koumis (boisson à base de lait fermenté);71;FR;'),
  ('Crème sure;72;FR;'),
  ('Yaourt;73;FR;'),
  ('Albumine;74;FR;'),
  ('albumen;75;FR;'),
  ('Conalbumine;76;FR;'),
  ('Substituts des oeufs;77;FR;'),
  ('Globuline;78;FR;'),
  ('Livetine;79;FR;'),
  ('Lysozyme;80;FR;'),
  ('ovalbumine;81;FR;'),
  ('ovomucine;82;FR;'),
  ('ovotransferrine;83;FR;'),
  ('Silico-albuminate;84;FR;'),
  ('Vitelline;85;FR;'),
  ('anchois;86;FR;'),
  ('Weizen;1;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:304:0018:0063:DE:PDF'),
  ('Roggen;2;DE;'),
  ('Gerste;3;DE;'),
  ('Hafer;4;DE;'),
  ('Dinkel;5;DE;'),
  ('Kamut;6;DE;'),
  ('Meeresfrüchte;7;DE;'),
  ('Garnele;8;DE;www.leo.org'),
  ('Gamba;9;DE;www.leo.org'),
  ('Ei;10;DE;'),
  ('Eier;11;DE;'),
  ('Fish;12;DE;'),
  ('Erdnussbutter;13;DE;'),
  ('Erdnuss;14;DE;'),
  ('Erdnussbutter;15;DE;http://de.wikipedia.org/wiki/Erdnussbutter'),
  ('Erdnussöl;16;DE;'),
  ('Soja;17;DE;'),
  ('Soja;18;DE;'),
  ('Soja;19;DE;'),
  ('Sojaöl;20;DE;'),
  ('Sojaöl;21;DE;'),
  ('Milch;22;DE;'),
  ('Laktose;23;DE;'),
  ('Mandel;24;DE;'),
  ('Haselnüsse;25;DE;'),
  ('Walnüsse;26;DE;'),
  ('Cashewkerne;27;DE;'),
  ('Pekannüsse;28;DE;'),
  ('Paranüsse;29;DE;'),
  ('Pistazien;30;DE;'),
  ('Macadamianüsse;31;DE;'),
  ('Macadamianüsse;32;DE;'),
  ('Sellerie;33;DE;'),
  ('Senf;34;DE;'),
  ('Senfsamen;35;DE;'),
  ('Sesam;36;DE;'),
  ('Sesamsamen;37;DE;'),
  ('Sesamöl;38;DE;'),
  ('Schwefeldioxid;39;DE;'),
  ('Sulphite ;40;DE;'),
  ('Lupine;41;DE;'),
  ('Lupine;42;DE;'),
  ('Mollusken;43;DE;'),
  ('Laktoglobulin;44;DE;isodisnatura.de'),
  ('Kasein;45;DE;isodisnatura.de'),
  ('Kaseinferment;46;DE;http://labelys.fr/index.php?cat=24&lang=de'),
  ('Kaseinat;47;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2010:118:0045:0055:DE:PDF'),
  ('Ammonium-Kaseinat ;48;DE;'),
  ('Kalziumkaseinat ;49;DE;'),
  ('Kaliumkaseinat;50;DE;'),
  ('Kaliumkaseinat;51;DE;'),
  ('Natriumkaseinat;52;DE;'),
  ('Laktalbumin;55;DE;'),
  ('Molke;59;DE;'),
  ('Molkenproteinkonzentrat;60;DE;'),
  ('Butter;61;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2006:299:0009:0010:DE:PDF'),
  ('Buttermilch;62;DE;'),
  ('Käse;63;DE;'),
  ('Käsebruch;64;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:C:2007:278:0017:0021:DE:PDF'),
  ('Kreme;65;DE;'),
  ('Eiskreme;66;DE;'),
  ('Ghee;67;DE;'),
  ('Kefir;68;DE;'),
  ('Kefir;69;DE;'),
  ('Kumiss;70;DE;'),
  ('Kumiss;71;DE;'),
  ('Sauerrahm;72;DE;'),
  ('Joghurt;73;DE;'),
  ('Eieralbumin;74;DE;'),
  ('Eiweiß;75;DE;'),
  ('Globulin;78;DE;'),
  ('Lysozym;80;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2001:278:0009:0010:DE:PDF'),
  ('Eieralbumin;81;DE;'),
  ('Ovomucin;82;DE;'),
  ('Sardelle;86;DE;'),
  ('tilapia;131;FR;'),
  ('tilapia;131;DE;'),
  ('Pangasius;166;EN;'),
  ('Pangasius;167;DE;'),
  ('Pangasius;168;FR;'),
  ('basa;87;DE;'),
  ('poisson-chat du Mékong;87;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Forelle;133;DE;'),
  ('cabillaud;98;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Kabeljau;98;DE;http://nock-gmbh-foodprocessing.com/en/produkte/fisch-enthaeutungsmaschinen/skinex-sb-495.php?navanchor=1010015'),
  ('loup;92;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Seewolf;92;DE;http://nock-gmbh-foodprocessing.com/en/produkte/fisch-enthaeutungsmaschinen/skinex-sb-495.php?navanchor=1010015'),
  ('calmar;164;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Tintenfisch;164;DE;http://nock-gmbh-foodprocessing.com/en/produkte/fisch-enthaeutungsmaschinen/skinex-sb-495.php?navanchor=1010015'),
  ('merlu;103;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Seehecht;103;DE;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2007:340:0077:0078:DE:PDF'),
  ('saumon;123;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Lachs;123;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('truite;133;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('anguille;99;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Aal;99;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('bar;167;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Seebarsch;167;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('Sea bass;167;EN;'),
  ('daurade;90;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Goldbrasse;90;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('carpe;91;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Karpfen;91;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('silure;168;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Welse;168;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('sheatfish;168;EN;'),
  ('turbot;137;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Steinbutt;137;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('écrevisse;141;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Krebse;141;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('crevettes;150;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Garnelen;150;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('huîtres;159;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Austern;159;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en'),
  ('moules;157;FR;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:070:0022:0023:FR:PDF'),
  ('Muscheln;157;DE;http://europa.eu/rapid/pressReleasesAction.do?reference=IP/92/887&format=HTML&aged=1&language=EN&guiLanguage=en');