class IngredientName < ActiveRecord::Base
  # model ingredients_name is a plural generated by automatic scafolding script from rails: IGNORE IT, DON'T USE IT, IT IS USELESS
  # appears in Data model, just for back up (View >> Show Model Dependency Diagram -- or -- CTRL + ALT + D)

  belongs_to :locale
  belongs_to :ingredient



  attr_accessible :title, :body
end
